site_name: TaskFlow API
site_url: https://github.com/thankfulfor/taskflow-api-docs
theme:
  name: readthedocs
nav:
  - Главная: index.md
  - Быстрый старт: getting-started.md
  - Справочник API: api.md
plugins:
  - redoc-tag
extra_javascript:
  - javascripts/i18n-nav.js
