site_name: Swagger Petstore API Docs
site_url: https://thankfulfor.github.io/petstore-api-docs/
theme:
  name: readthedocs
nav:
  - Главная: index.md
  - Быстрый старт: getting-started.md
  - Справочник API: api.md
  - Версии API: versions.md
  - Changelog: changelog.md
plugins:
  - search
  - redoc-tag
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/i18n-nav.js
